SUBROUTINE KERNEL(N, ALIVE, NUMNEIGHBORS, NEIGHBORS)
  IMPLICIT NONE

  INTEGER :: I,J,K

!!$  !These must match the #define statements in main.cpp  
  INTEGER, PARAMETER :: N_MAX = 20
  INTEGER, PARAMETER :: MAX_NEIGHBORS = 20

  INTEGER :: N 
  REAL*8, DIMENSION(N_MAX) :: ALIVE
  INTEGER, DIMENSION(N_MAX) :: NUMNEIGHBORS
  INTEGER, DIMENSION(MAX_NEIGHBORS,N_MAX) :: NEIGHBORS

  REAL*8, DIMENSION(N_MAX) :: NEW_ALIVE            
  
  !TEMP VARIABLES
  REAL*8 :: SUM

  ! DEBUGGING
  PRINT*, "FORTRAN:  N=",N

  
  !LOOP OVER NODES
  DO I=1,N
     PRINT*, "FORTRAN: NODE=", I, "ALIVE = ", ALIVE(I)
     PRINT*, "FORTRAN: NODE=", I, "NUMNEIGHBORS = ", NUMNEIGHBORS(I)
     
     NEW_ALIVE(I)=0d0
     IF(ALIVE(I).eq.1d0) THEN
        NEW_ALIVE(I)=0d0
        DO J=1,NUMNEIGHBORS(I)
           PRINT*, "I=",I, "NEIGHBOR=", NEIGHBORS(J,I)+1
        ENDDO
     ELSE
        SUM=0d0
        DO J=1,NUMNEIGHBORS(I)
           SUM=SUM+ALIVE(NEIGHBORS(J,I)+1)
           PRINT*, "I=",I, "NEIGHBOR=", NEIGHBORS(J,I)+1, "NEIGHBOR ALIVE=", ALIVE(NEIGHBORS(J,I)+1)
        ENDDO
        IF(SUM.gt.0d0)THEN
           PRINT*, "SUM=", SUM
           NEW_ALIVE(I)=1d0
        ENDIF
     ENDIF
              PRINT*, "FORTRAN: I=",I," NEW_ALIVE=",NEW_ALIVE(I)
  ENDDO
  
  
  DO I=1,N
     ALIVE(I)=NEW_ALIVE(I)
  ENDDO


  ! RETURN 0 IF NO CELLS ARE ALIVE
  DO I=1,N
     IF (ALIVE(I).eq.1d0) THEN
        RETURN 1
     ENDIF
  END DO
  
  RETURN 0

END SUBROUTINE KERNEL
